travis:
  secure:
    BINSTAR_TOKEN: j86c2wCPEjfvWTTGmB4voreWWXWG1qr+IuYWp2KpUgGYgpVyvsOoY6bz+orV3KyIyUW/NLGhpc3q0EkqMC36eIlY7JqwLcmtKxScEvX//qERSwkzfYcaZTE9C10JZp0eWkC8ZAKFiRVKhtVeFm7IqCclcMk8iO876IOOXHDbqwdYJJ86GOuoKqWpT1WUyaxkWfPOzksTCKScMu0+Q244gd8F2pKXfxXgP/9dYs3PX1xAkuWQlc7KBaBrVrRTeqhph+NJZQhN3716/CZIHpJ5SJZHY9q7SpppXDYdJl8GU0zNgnT+fhDk7HX+yR9IWm+/2YrUBYCTH2jygjgmZ71+gDOhGg1JkVE5zkFWH4QaTRpYSbM08f+OcrLBNFZz+gqRrFBs5AUaimqgT3XIh6YwIvXkRLftNGmbp1tH8UXI91FcOD0XL5oc1k8qGurP+QmH8A6OZT/yKNkpcNJd8hfTP8TdMvLHGK7WhefdVhNvEh27xtaVCr98u1Vu+/erDjEe8Jubgkdd1mQ11e7Z9IrGH23xIsX/s9OQflSsnUdta2vMrEVOGtmQEps31J6DV3ou6+q0xRWP04zo56/6ycuUj9qoU6y+MEDhER6OxjGum0EqgYfkHygCTYavLDIjnM0s1P31gl15PX6j7fDtDrii1RAsKOXWT5OoOfmgTPvmaCg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
