appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Q514hu/aCNwxad6TJHkDbHGaatFPNaZamYhhtLqmFT6+CwqSM5X1bKdWbCr/ZGBKlIw0S6ezAt90iSa4QdQ1YckJJd2KxyGOH1zPCEj90ILVOrWedBFE+QvjWuop3c6esw/mRWPNnHAd8Pn/BUsKKig2ovZlKaoks2NS5o0AbzbekU+goFAnEHLEJUK83esfAo6exxie9bZuFj6IZ3CEuzBM7SSeEwZnPmWQ7LZyFCOPI0XaVo61oSpiNWQvmMNbfeBDjDWKpJobTsArE06tdKDjPZf67dCZiqvCeZhEddJLzTxn0mXyR2LUYhor1Gu7LWa3sJFIPQg+pozDORBexX074x7lmsAIvBIZJ5Wx0xAAFCRGzatqTD9xPfwb+QxioIXeqjuGVNVpazTa+cXkx2nM1kvm1AD+mtRywEVGBH8ALS9Mxqj6rAogISdQftAh7dTXvvE9zHdB7s7VXx1u7Nq95HClfKiQjUFCjZ/VYenklMumm0uamil8yy/pR7Eq3IjtYy6IXqPkl5jUQ81suLFj+MFDNXmLqBw64s19yq4xXwDtembLa4gFT8pyFU5MKGP7xdrci8lTDq4y/h0nqOyAr5aXFkzS8+uIUHuqIhnq7g4ODOQi+Ky8qtMuio/I1AWbYCGQ6xiONYC1giZ7AHEvVZDlFfpUwfbzPwdNTd8=
